### ISSUE TITLE
Slider troughs are too wide

### ISSUE THREAD

**Issue by georgelemental** [nana-4/Flat-Plat#113]
- Flat-Plat version: Latest from git
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`): 3.22.11
- Distribution (and version): Ubuntu GNOME 17.04
- Desktop environment (and version): Gnome 3.24
- Related application (and version): All GTK applications with sliders
- Steps to reproduce: Open a GTK application with a slider
- Screenshots:

What Flat-Plat currently looks like (GTK Widget Factory):
![Flat-Plat](https://cloud.githubusercontent.com/assets/11415479/25644219/5a4a5116-2f72-11e7-9ed4-e88692977838.png)

The Material Design spec (https://material.io/guidelines/components/sliders.html): 
![Material Design](https://cloud.githubusercontent.com/assets/11415479/25644255/a6f6d2a0-2f72-11e7-9c5b-0175c4ccc1ab.png)

The material design slider troughs are 2 pixels wide (tall?), but Flat-Plat's slider troughs are twice that (4 pixels). Is this intentional, or is it a (very minor) bug?

**Comment by nana-4** [comment]
Yes, this was intentional. Because I felt that 2px trough (and 12px slider) is too thin/small compared to other widgets (e.g. 36px buttons). For _non-compact_ variants, the [switch](https://material.io/guidelines/components/selection-controls.html#selection-controls-switch) is also getting bigger for the same reason.

This is one of the reasons that I call this theme is a _Material Design-like_ theme.

However, this design decision is not permanent. Perhaps it may require more feedback or discussion.

**Comment by georgelemental** [comment]
How would one go about changing this manually?

**Comment by nana-4** [comment]
Here's quick way:

1. Open `/usr/share/themes/Flat-Plat<-variant>/gtk-3.22/gtk.css` with a text editor.

2. Go to line `2484` and edit to `margin: -11px;`.

  ```css
  scale slider {
    min-height: 24px;
    min-width: 24px;
    margin: -11px;
  }
  ```

3. Go to line `2516` and edit to `background-size: calc(100% - 12px);`.

  ```css
  scale slider {
    transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    background-repeat: no-repeat;
    background-position: center;
    background-size: calc(100% - 12px);
  }
  ```

4. Go to line `2528` and edit to `background-size: calc(100% - 10px);`.

  ```css
  scale slider:hover {
    background-size: calc(100% - 10px);
  }
  ```

5. Go to line `2532` and edit to `background-size: calc(100% - 6px);`.

  ```css
  scale slider:active {
    background-size: calc(100% - 6px);
  }
  ```

6. Reload the theme! ;)

**Comment by nana-4** [comment]
Okay, if you know how to handle Sass, you can do the following:

Around `2166` lines of `_common.scss`:
```css
  $slider_margin: -($slider_size - 2px) / 2;
  $marks_slider_margin: -($marks_slider_size - 2px) - $slider_margin;
```

Around `2224` lines:
```css
    background-size: calc(100% - 12px);

    &:hover { background-size: calc(100% - 10px); }

    &:active { background-size: calc(100% - 6px); }
```

And on line `2291` and below also like this:
```css

              background-position: center calc(100% - 6px);

              &:hover { background-position: center calc(100% - 5px); }

              &:active { background-position: center calc(100% - 3px); }
```
