### ISSUE TITLE
Change Location Bar Color & Transparency

### ISSUE THREAD

**Issue by DAZE95** [nana-4/Flat-Plat#94]
Manjaro 16.10
Gnome 3.22.2
GTK+  3.22.4
V3.22.20161109

Hi
first of all I want to say is that this is a very nice theme! I have change the colors of the theme but at a point of customization I don't make progress. How can I change the color of the location bar?
![bildschirmfoto vom 2016-12-12 02-28-08](https://cloud.githubusercontent.com/assets/24514166/21085456/ad6afdfc-c012-11e6-9060-6a693c0873d2.png)
And I have no transparency in this theme. Is there a possibilty to create some transparency?

**Comment by nana-4** [comment]
> first of all I want to say is that this is a very nice theme!

Thanks. :)

> How can I change the color of the location bar?

If you are customizing with Sass, just change the value of `$titlebar_indicator_color` in `_colors.scss`.

If you are editing CSS directly, move around line 847 and replace the two `currentColor` with your color.


```css
  .titlebar:not(headerbar) button:not(.suggested-action):not(.destructive-action),
  headerbar button:not(.suggested-action):not(.destructive-action) {
    border-image: radial-gradient(circle closest-corner at center calc(100% - 1px), #AABBCC 0%, transparent 0%) 0 0 0/0 0 0px; }
    .titlebar:not(headerbar) button:not(.suggested-action):not(.destructive-action):checked,
    headerbar button:not(.suggested-action):not(.destructive-action):checked {
      border-image: radial-gradient(circle closest-corner at center calc(100% - 1px), #AABBCC 100%, transparent 0%) 0 0 2/0 0 2px; }
```

>  And I have no transparency in this theme. Is there a possibilty to create some transparency?

Sorry but I have no idea what are you talking about.
Do you mean that you want to make the headerbar translucent? If so, I don't know how to change it and I have no plan to make it translucent. Please refer to other themes.
